'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Download, ExternalLink, Loader2, Receipt } from 'lucide-react';
import { getMyInvoicesAction, type MyInvoice } from '@/lib/company-profile-actions';

function formatAmount(cents: number, currency: string, locale: string) {
  return new Intl.NumberFormat(locale === 'en' ? 'en-IE' : 'it-IT', {
    style: 'currency',
    currency: (currency || 'eur').toUpperCase(),
  }).format(cents / 100);
}

function formatDate(unix: number, locale: string) {
  return new Date(unix * 1000).toLocaleDateString(locale === 'en' ? 'en-IE' : 'it-IT', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

function statusBadge(status: string) {
  const map: Record<string, { label: string; cls: string }> = {
    paid: { label: 'Pagato', cls: 'bg-green-500/15 text-green-600 border-green-500/30' },
    open: { label: 'In sospeso', cls: 'bg-orange-500/15 text-orange-600 border-orange-500/30' },
    draft: { label: 'Bozza', cls: 'bg-muted text-muted-foreground border-border' },
    void: { label: 'Annullato', cls: 'bg-red-500/15 text-red-600 border-red-500/30' },
    uncollectible: { label: 'Non riscuotibile', cls: 'bg-red-500/15 text-red-600 border-red-500/30' },
  };
  const v = map[status] ?? { label: status, cls: 'bg-muted text-muted-foreground' };
  return <Badge variant="outline" className={v.cls}>{v.label}</Badge>;
}

export default function HubBillingPage() {
  const params = useParams();
  const locale = (params?.locale as string) === 'en' ? 'en' : 'it';
  const en = locale === 'en';

  const [invoices, setInvoices] = useState<MyInvoice[] | null>(null);

  useEffect(() => {
    getMyInvoicesAction()
      .then((data) => setInvoices(data))
      .catch(() => setInvoices([]));
  }, []);

  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-10">
      <Link
        href={`/${locale}/hub/company-profile`}
        className="mb-2 inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground"
      >
        <ArrowLeft className="h-3 w-3" /> {en ? 'Back' : 'Indietro'}
      </Link>
      <h1 className="mb-2 text-2xl font-bold">{en ? 'Billing' : 'Fatturazione'}</h1>
      <p className="mb-6 text-sm text-muted-foreground">
        {en
          ? 'All payments and receipts for your Company Page subscription. Download invoices anytime — they are generated by Stripe.'
          : 'Tutti i pagamenti e le ricevute del tuo abbonamento Pagina Aziendale. Scarica le fatture quando vuoi — sono generate da Stripe.'}
      </p>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <Receipt className="h-5 w-5 text-primary" />
            {en ? 'Invoices' : 'Fatture'}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {invoices === null ? (
            <div className="flex justify-center py-10">
              <Loader2 className="h-5 w-5 animate-spin text-primary" />
            </div>
          ) : invoices.length === 0 ? (
            <p className="py-6 text-center text-sm text-muted-foreground">
              {en
                ? "No invoices yet. They'll show up here after your first paid renewal."
                : 'Nessuna fattura per ora. Compariranno qui dopo il primo rinnovo pagato.'}
            </p>
          ) : (
            <div className="space-y-2">
              {invoices.map((inv) => (
                <div
                  key={inv.id}
                  className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border/40 bg-card/50 p-4 transition-colors hover:border-primary/30"
                >
                  <div className="flex-1 min-w-0">
                    <div className="flex flex-wrap items-center gap-2">
                      <p className="font-mono text-sm font-semibold">
                        {inv.number || inv.id.slice(0, 14)}
                      </p>
                      {statusBadge(inv.status)}
                    </div>
                    <p className="mt-1 text-xs text-muted-foreground">
                      {formatDate(inv.created, locale)} · {formatAmount(inv.amountPaid, inv.currency, locale)}
                    </p>
                  </div>
                  <div className="flex gap-2">
                    {inv.invoicePdfUrl && (
                      <Button asChild size="sm" variant="outline">
                        <a href={inv.invoicePdfUrl} target="_blank" rel="noreferrer">
                          <Download className="mr-1 h-3.5 w-3.5" />
                          PDF
                        </a>
                      </Button>
                    )}
                    {inv.hostedInvoiceUrl && (
                      <Button asChild size="sm" variant="ghost">
                        <a href={inv.hostedInvoiceUrl} target="_blank" rel="noreferrer">
                          <ExternalLink className="h-3.5 w-3.5" />
                        </a>
                      </Button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      <p className="mt-4 text-xs text-muted-foreground">
        {en
          ? 'Note: these are Stripe receipts. For Italian e-invoices (fattura elettronica via SDI) we issue them manually using the SDI/PEC info you provided in your profile.'
          : 'Nota: queste sono ricevute Stripe. Per le fatture elettroniche italiane (via SDI) le emettiamo manualmente usando il Codice Destinatario / PEC che hai indicato nel profilo.'}
      </p>
    </div>
  );
}
